services:
  apollo-server:
    build: .
    container_name: api_gql_server
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpass
      APOLLO_PORT: 4000
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net:
    name: backend-net
    driver: bridge
    external: true